-- DO NOT EDIT!
-- This file was generated automatically
-- using tools/gendeps.lua.

dofile 'engine/events.lua'
dofile 'engine/diary.lua'

dofile 'src/day1/act4/tract_camp/tract_camp.room.lua'
dofile 'src/day1/act1/fields/victim.obj.lua'
dofile 'src/day1/act1/fields/smith_hammer.lua'
dofile 'src/day1/act1/fields/fields.room.lua'
dofile 'src/day1/act1/fields/warren.person.lua'
dofile 'src/day1/act1/state.lua'
dofile 'src/day1/act1/square/square.room.lua'
dofile 'src/day1/act1/square/new_bow.obj.lua'
dofile 'src/day1/act1/square/well.obj.lua'
dofile 'src/day1/act1/square/mirror.obj.lua'
dofile 'src/day1/act1/square/holy_sign.obj.lua'
dofile 'src/day1/act1/square/blacksmith.person.lua'
dofile 'src/day1/act1/square/elder.person.lua'
dofile 'src/day1/act1/home/food.obj.lua'
dofile 'src/day1/act1/home/hunting_gear.obj.lua'
dofile 'src/day1/act1/home/trophies.obj.lua'
dofile 'src/day1/act1/home/home.room.lua'
dofile 'src/day1/act1/home/journal.obj.lua'
dofile 'src/day1/act1/home/posters.obj.lua'
dofile 'src/day1/act3/uh_prison/uh_prison.room.lua'
dofile 'src/day1/act3/uh_square/uh_square.room.lua'
dofile 'src/day1/act3/uh_pit/uh_pit.room.lua'
dofile 'src/day1/act3/uh_pavilion/uh_pavilion.room.lua'
dofile 'src/day1/act3/uh_camp/uh_camp.room.lua'
dofile 'src/day1/act2/lords_lands/lords_lands.room.lua'
dofile 'src/day1/act2/lords_lake/lords_lake.lua'
dofile 'src/day1/act2/afterparty/afterparty.lua'
dofile 'src/day1/act2/wet_cave/the_thing.obj.lua'
dofile 'src/day1/act2/wet_cave/wet_cave.room.lua'
dofile 'src/day1/act2/forest_edge/forest_edge.room.lua'
dofile 'src/day1/act2/thicket/thicket.room.lua'
dofile 'src/day1/act2/thicket/deer.obj.lua'
dofile 'src/day1/act2/private_lands/forester.obj.lua'
dofile 'src/day1/act2/private_lands/private_lands.room.lua'
dofile 'src/main.room.lua'
dofile 'src/quests.lua'
